<?php
	$SourceSuccessfullyAdded = "Source successfully added!";
	$AddNewSource = "Add a New Source";
	$MetadataIDSemicolon = "MetadataID:";
	$MetadataAutoGenerated = "(This will be auto-generated for you upon submission.)";
	$AddSourceButton = "Add Source";
?>
