<?php
	$SourceSuccessfullyAdded = "¡Fuente añadida correctamente!";
	$AddNewSource = "Añadir una nueva fuente";
	$MetadataIDSemicolon = "MetadataID:";
	$MetadataAutoGenerated = "(Esto se generará automáticamente al momento del envío.)";
	$AddSourceButton = "Agregar fuente";
?>


